name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: services/catalog

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: olafurpg/setup-scala@v11
      - name: "Starting up Postgres & Redis ğŸ³"
        run: |
          echo "Running catalog"
          docker network create catalog
          make local.postgres.start

      - name: Tests
        run: |
          source .env.it
          sbt -J-Xms4G -J-Xmx4G test it:test

      - name: "Shutting down Postgres & Redis ğŸ³"
        run: |
          docker-compose down
